name: Testing

on: push

env: "${{import.meta.env.VITE_API_URL}}"

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ Git checkout
        uses: actions/checkout@v4

      - name: ğŸ’¾ Install modules
        run: npm ci

      - name: ğŸ§ª Testing
        run: npm test
